openapi: 3.0.0
info:
  title: Currency convert

  contact: {}
  version: '1.0'
servers:
  - url: 'https://jaya-currency-converter.herokuapp.com'
    description: Heroku
  - url: 'http://localhost:7000'
    description: Localhost
paths:
  /transactions:
    post:
      tags:
        - Transactions
      summary: Calculates currency conversion
      operationId: convert

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversionDto'
            example:
              from: 'BRL'
              to: 'USD'
              amount: 100.00
              userId: 1
        required: true
        x-send-file-in-body: false
      responses:
        '201':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        '400':
          description: "Bad request"
    get:
      tags:
        - Transactions
      summary: "retrieves all transactions performed by user"
      parameters:
        - in: query
          name: user
          required: true
          description: User id
          schema:
            type: "integer"
            format: "int64"

      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"

components:
  schemas:
    Transaction:
      title: Transaction
      type: object
      properties:
        id:
          type: "integer"
          format: "int64"
        userId:
          type: "integer"
          format: "int64"
        originCurrency:
          type: "string"
          enum: [BRL, USD, EUR, JPY]
        originAmount:
          type: "number"
          format: "double"
        destinationCurrency:
          type: "string"
          enum: [BRL, USD, EUR, JPY]
        destinationAmount:
          type: "number"
          format: "double"
        exchangeRate:
          type: "number"
          format: "double"
        date:
          type: "number"

    ConversionDto:
      title: ConversionDto
      required:
        - from
        - to
        - amount
        - userId
      type: object
      properties:
        from:
          type: string
          enum: [BRL, USD, EUR, JPY]
        to:
          type: string
          enum: [BRL, USD, EUR, JPY]
        amount:
          type: number
          format: "double"
        userId:
          type: number
          format: "int64"
      example:
        from: 'BRL'
        to: 'USD'
        amount: 100
        userId: 1

    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        body:
          type: array
          items:
            type: string

tags:
  - name: Transactions