openapi: 3.0.0
info:
  title: Currency convert
  description: |-

  contact: {}
  version: '1.0'
servers:
  - url: 'http://localhost:7000'
    variables: {}
paths:
  /transactions:
    post:
      tags:
        - Convert
      summary: Currency Conversion Calculator
      operationId: convert

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              from: 'BRL'
              to: 'USD'
              amount: 100
              userId: 1
        required: true
        x-send-file-in-body: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    RegisterRequest:
      title: Currency conversion
      required:
        - from
        - to
        - amount
        - userId
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        amount:
          type: number
        userId:
          type: number
      example:
        from: 'BRL'
        to: 'USD'
        amount: 100
        userId: 1
tags:
  - name: Convert